# Generated by Django 5.2.17 on 2026-09-18 06:52

import apps.invitations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('management_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sender_name', models.CharField(max_length=80)),
                ('recipient_name', models.CharField(max_length=80)),
                ('main_message', models.CharField(max_length=240)),
                ('personal_message', models.TextField(blank=True)),
                ('question_text', models.CharField(default='Would you go on a date with me?', max_length=240)),
                ('decline_message', models.CharField(blank=True, default='Maybe another time?', max_length=240)),
                ('theme', models.CharField(choices=[('minimal', 'Minimal'), ('romantic', 'Romantic'), ('sunset', 'Sunset'), ('night', 'Night'), ('soft', 'Soft'), ('elegant', 'Elegant')], default='elegant', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('planning', 'Planning'), ('confirmed', 'Confirmed')], db_index=True, default='created', max_length=20)),
                ('show_welcome', models.BooleanField(default=True)),
                ('show_personal_message', models.BooleanField(default=True)),
                ('show_memories', models.BooleanField(default=False)),
                ('allow_multiple_activities', models.BooleanField(default=False)),
                ('music', models.FileField(blank=True, null=True, upload_to=apps.invitations.models.invitation_music_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='invitations.availabledate')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='invitations.invitation')),
            ],
            options={
                'ordering': ['time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='availabledate',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='invitations.invitation'),
        ),
        migrations.CreateModel(
            name='ActivityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvitationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.invitations.models.invitation_photo_upload)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.invitations.models.memory_image_upload)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='invitations.invitation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=16)),
                ('selected_time', models.TimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='invitations.invitation')),
                ('selected_activities', models.ManyToManyField(blank=True, related_name='responses', to='invitations.activityoption')),
                ('selected_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='invitations.availabledate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='availabledate',
            constraint=models.UniqueConstraint(fields=('invitation', 'date'), name='unique_invitation_date'),
        ),
    ]
