# Generated by Django 5.2.17 on 2026-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientresponse',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
