# Generated by Django 5.2.17 on 2026-09-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_recipientresponse_decline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='finale_note_type',
            field=models.CharField(choices=[('letter', 'Letter'), ('review', 'Review'), ('none', 'None')], default='letter', max_length=16),
        ),
        migrations.AddField(
            model_name='invitation',
            name='greeting',
            field=models.CharField(blank=True, default='Hi, beautiful', max_length=80),
        ),
        migrations.AddField(
            model_name='invitation',
            name='unlock_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='invitation',
            name='unlock_hint',
            field=models.CharField(blank=True, default='The password is the date of our first date', max_length=240),
        ),
        migrations.AddField(
            model_name='recipientresponse',
            name='finale_note',
            field=models.TextField(blank=True),
        ),
    ]
